name: Pipeline Security Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        working-directory: ./fastapi
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Security Gate 1 - Testes unitários
        working-directory: ./fastapi
        run: python -m pytest -v